site_name: ZARUJU

theme:
    font:
      text: Noto Sans JP
      code: Inconsolata

    logo:
    favicon:

    name: 'material'
    palette:

    # Light mode
    - scheme: slate
      primary: blue
      accent: blue

    features:
      - navigation.top

extra:
  generator: false
  homepage: https://zaruju.github.io/
  social:
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/mebiusbox2
    #   name: mebiusbox2 on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/ZARUJU

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      # 行番号の付加
      # linenums: true
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - admonition

plugins:
  - search
  - roamlinks 


extra_javascript:
  - _javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
